# Generated by Django 2.2.14 on 2020-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='tests',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
