# Generated by Django 2.2.14 on 2020-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200731_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BigIntegerField()),
            ],
        ),
    ]
